"""initial schema

Revision ID: 4bd334951e69
Revises: 
Create Date: 2026-02-21 22:54:27.620609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd334951e69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('solar_kwh', sa.Float(), nullable=True),
    sa.Column('grid_import_kwh', sa.Float(), nullable=True),
    sa.Column('grid_export_kwh', sa.Float(), nullable=True),
    sa.Column('load_kwh', sa.Float(), nullable=True),
    sa.Column('self_consumed_kwh', sa.Float(), nullable=True),
    sa.Column('peak_solar_w', sa.Float(), nullable=True),
    sa.Column('estimated_savings_thb', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_summaries_date'), 'daily_summaries', ['date'], unique=True)
    op.create_table('data_solar_intensity_2560',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('subdistrict_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('intensity_mj_m2_day', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_solar_intensity_2560_district_id'), 'data_solar_intensity_2560', ['district_id'], unique=False)
    op.create_index(op.f('ix_data_solar_intensity_2560_province_id'), 'data_solar_intensity_2560', ['province_id'], unique=False)
    op.create_index(op.f('ix_data_solar_intensity_2560_subdistrict_id'), 'data_solar_intensity_2560', ['subdistrict_id'], unique=False)
    op.create_table('energy_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('solar_power_w', sa.Float(), nullable=True),
    sa.Column('grid_power_w', sa.Float(), nullable=True),
    sa.Column('load_power_w', sa.Float(), nullable=True),
    sa.Column('battery_soc', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_readings_timestamp'), 'energy_readings', ['timestamp'], unique=False)
    op.create_table('monthly_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('solar_kwh', sa.Float(), nullable=True),
    sa.Column('grid_import_kwh', sa.Float(), nullable=True),
    sa.Column('grid_export_kwh', sa.Float(), nullable=True),
    sa.Column('load_kwh', sa.Float(), nullable=True),
    sa.Column('self_consumed_kwh', sa.Float(), nullable=True),
    sa.Column('estimated_savings_thb', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'viewer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('solar_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('system_capacity_kw', sa.Float(), nullable=False),
    sa.Column('panel_count', sa.Integer(), nullable=False),
    sa.Column('panel_efficiency', sa.Float(), nullable=True),
    sa.Column('performance_ratio', sa.Float(), nullable=True),
    sa.Column('degradation_rate', sa.Float(), nullable=True),
    sa.Column('installation_cost_thb', sa.Float(), nullable=False),
    sa.Column('electricity_tariff_thb', sa.Float(), nullable=True),
    sa.Column('tariff_escalation_rate', sa.Float(), nullable=True),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('subdistrict_id', sa.Integer(), nullable=False),
    sa.Column('feed_in_tariff_thb', sa.Float(), nullable=True),
    sa.Column('self_consumption_ratio', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solar_configs')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('outbox_events')
    op.drop_table('monthly_summaries')
    op.drop_index(op.f('ix_energy_readings_timestamp'), table_name='energy_readings')
    op.drop_table('energy_readings')
    op.drop_index(op.f('ix_data_solar_intensity_2560_subdistrict_id'), table_name='data_solar_intensity_2560')
    op.drop_index(op.f('ix_data_solar_intensity_2560_province_id'), table_name='data_solar_intensity_2560')
    op.drop_index(op.f('ix_data_solar_intensity_2560_district_id'), table_name='data_solar_intensity_2560')
    op.drop_table('data_solar_intensity_2560')
    op.drop_index(op.f('ix_daily_summaries_date'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    # ### end Alembic commands ###
